package com.framework.jdbc;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.*;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.support.rowset.SqlRowSet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by thushear on 2015/8/31.
 */
public class JdbcTemplateTest {


    static JdbcTemplate jdbcTemplate ;


    @BeforeClass
    public static void setUpBeforeClass () {
        String hqldb = "jdbc:hsqldb:mem:test";
        String userName = "sa";
        String password = "";
        DriverManagerDataSource driverManagerDataSource = new DriverManagerDataSource(hqldb,userName,password);
        driverManagerDataSource.setDriverClassName("org.hsqldb.jdbcDriver");
        jdbcTemplate = new JdbcTemplate(driverManagerDataSource);
    }


    @Before
    public void setUp(){
        //id自增主键从0开始
        String createTableSql = "create memory table test" +
                "(id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name varchar(100))";
        jdbcTemplate.update(createTableSql);
        String createHsqldbFunctionSql =
                "CREATE FUNCTION FUNCTION_TEST(str VARCHAR(100)) " +
                        "returns INT begin atomic return length(str);end";

        jdbcTemplate.update(createHsqldbFunctionSql);

        String createHsqldbProcedureSql =
                "CREATE PROCEDURE PROCEDURE_TEST" +
                        "(INOUT inOutName VARCHAR(100), OUT outId INT) " +
                        "MODIFIES SQL DATA " +
                        "BEGIN ATOMIC " +
                        "  insert into test(name) values (inOutName); " +
                        "  SET outId = IDENTITY(); " +
                        "  SET inOutName = 'Hello,' + inOutName; " +
                        "END";
        jdbcTemplate.execute(createHsqldbProcedureSql);
        testInsert();
        //test();
    }



    @After
    public void tearDown(){
        jdbcTemplate.execute("DROP  FUNCTION  FUNCTION_TEST");
        jdbcTemplate.execute("DROP  PROCEDURE PROCEDURE_TEST");
        jdbcTemplate.execute("DROP TABLE test ");
    }




    @Test
    public void test(){
        String sql = "select * from INFORMATION_SCHEMA.SYSTEM_TABLES";
        jdbcTemplate.query(sql, new RowCallbackHandler() {
            @Override
            public void processRow(ResultSet rs) throws SQLException {
                String value = rs.getString("TABLE_NAME");
                System.out.printf("tableName = %s \n" , value);
            }
        });



    }



    @Test
   public void testCRUD(){
        testInsert();
        testSelect();
        System.out.println("===============");
        testUpdate();
        testSelect();
        System.out.println("===============");
        testDelete();
        testSelect();

   }



    public void testInsert(){
        jdbcTemplate.update("INSERT  INTO  test(name) values('name1')");
        jdbcTemplate.update("INSERT INTO test(name) values('name2')");
        Map map = jdbcTemplate.queryForMap("SELECT * FROM test where name = 'name1'");
        System.out.printf("map = %s \n" , map);
        int count = jdbcTemplate.queryForInt("SELECT count(1) FROM test");
        System.out.printf("count = %d \n " ,count );
    }




    public void testSelect(){
        jdbcTemplate.query("select * from test", new RowCallbackHandler() {
            @Override
            public void processRow(ResultSet rs) throws SQLException {
                System.out.printf( "id = %d  ," , rs.getInt("id"));
                System.out.printf("name = %s \n" , rs.getString("name"));
            }
        });
    }




    public void testUpdate(){
        jdbcTemplate.update("update test set name = 'name3' where name = ?" , new Object[]{"name1"});
    }


    public void testDelete(){
        jdbcTemplate.update("delete from test where name = ?" , new Object[]{"name2"});
    }




    @Test
    public void testPreparedStatement() {
        int count = jdbcTemplate.execute(new PreparedStatementCreator() {
                                 @Override
                                 public PreparedStatement createPreparedStatement(Connection con) throws SQLException {

                                     return con.prepareStatement("SELECT COUNT(1) FROM test");
                                 }
                             },
                new PreparedStatementCallback<Integer>() {
                    @Override
                    public Integer doInPreparedStatement(PreparedStatement ps) throws SQLException, DataAccessException {
                       ps.execute();
                       ResultSet resultSet = ps.getResultSet();
                        resultSet.next();
                        return resultSet.getInt(1);
                    }
                }
        );
        System.out.printf("count = %s \n" , count);
    }


    @Test
    public void testPrepareStatement2(){
        int update = jdbcTemplate.update("INSERT  INTO test(name) values(?)", new PreparedStatementSetter() {
            @Override
            public void setValues(PreparedStatement ps) throws SQLException {
                ps.setString(1,"name5");
            }
        });
        System.out.printf("update =  %d \n" , update);
        testSelect();
    }



    @Test
    public void testResultSet1() {
        List<Map>  list = jdbcTemplate.query("select * from test", new RowMapper<Map>() {


            @Override
            public Map mapRow(ResultSet rs, int rowNum) throws SQLException {
                Map map = new HashMap();
                map.put(rs.getInt(1), rs.getString(2));
                return map;
            }
        });

        System.out.printf("list = %s \n" , list);
    }



    @Test
    public void testResultSet2() {
        final List result = new ArrayList();

        jdbcTemplate.query("select * from test", new RowCallbackHandler() {
            @Override
            public void processRow(ResultSet rs) throws SQLException {
                Map map = new HashMap();
                map.put(rs.getInt("id"),rs.getString("name"));
                result.add(map);
            }
        });

        System.out.printf("result = %s \n" , result);
    }


    @Test
    public void testResultSet3(){
        List result  =  jdbcTemplate.query("select * from test", new ResultSetExtractor<List>() {

            @Override
            public List extractData(ResultSet rs) throws SQLException, DataAccessException {
                List result = new ArrayList();
                while (rs.next()){
                    Map map = new HashMap();
                    map.put(rs.getInt("id") , rs.getString("name"));
                    result.add(map);
                }

                return result;
            }
        });

        System.out.printf("result = %s \n" , result);
    }



    @Test
    public void testQueryFor(){

        int count = jdbcTemplate.queryForInt("select COUNT(1) from test");
        System.out.printf("count = %d \n" , count);

        Map<String, Object> map = jdbcTemplate.queryForMap("select * from test where id=0");
        System.out.printf("map = %s \n" , map);

        List<Map<String, Object>> list =  jdbcTemplate.queryForList("select * from test");
        System.out.printf("queryList = %s \n" , list);

        int count1 = jdbcTemplate.queryForObject("select count(1) from test", Integer.class);
        System.out.printf("count1 = %d \n" , count1);

        SqlRowSet sqlRowSet =  jdbcTemplate.queryForRowSet("select * from test");

        while (sqlRowSet.next()){
            System.out.printf("sqlRowSet = %s \n" , sqlRowSet.getInt(1) + ":" + sqlRowSet.getString(2) );

        }

    }


}
